version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: deportes_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: deportes_db
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
